package io.github.bsels.javafx.maven.plugin.in.memory.compiler;

import javax.tools.FileObject;
import javax.tools.ForwardingJavaFileManager;
import javax.tools.JavaFileManager;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/// A custom implementation of [JavaFileManager] that stores compiled class files in memory.
///
/// Extends [ForwardingJavaFileManager] to delegate standard file manager operations
/// while providing an in-memory mechanism for storing the compiled bytecode of Java classes.
/// This implementation is specifically designed to capture the output of the Java compiler
/// during runtime and store it in a map for later retrieval or dynamic class loading.
///
/// This class is primarily used in scenarios involving runtime Java compilation
/// (e.g., converting FXML files to Java source code and then compiling them),
/// where compiled classes need to be accessed or loaded dynamically without relying on the physical filesystem.
public final class InMemoryCompiledClassOutputJavaFileManager extends ForwardingJavaFileManager<JavaFileManager> {

    /// A map that stores compiled classes in memory, where the key is the fully qualified class name
    /// and the value is an [InMemoryCompiledClass] instance representing the compiled class data.
    ///
    /// This map provides efficient in-memory storage and retrieval of Java classes that are compiled during runtime.
    /// It is particularly useful in scenarios involving dynamic or on-the-fly Java compilation,
    /// as it eliminates the need for filesystem-based storage.
    ///
    /// The keys in the map are [String] values representing fully qualified class names,
    /// ensuring that each compiled class can be uniquely identified.
    /// The values are instances of [InMemoryCompiledClass],
    /// which encapsulate the compiled bytecode and provide an output stream for the compiler to write into.
    ///
    /// This field is initialized during the construction of the containing class
    /// and is used to collect all classes generated by the compiler during a single compilation task.
    private final Map<String, InMemoryCompiledClass> compiledClasses;

    /// Constructs a new `InMemoryCompiledClassOutputJavaFileManager` instance.
    ///
    /// This file manager allows in-memory storage of compiled classes by intercepting output requests for class files
    /// while delegating all other standard operations (like source file lookup) to the provided base file manager.
    ///
    /// @param javaFileManager the underlying [JavaFileManager] to which operations will be delegated. Must not be null.
    /// @throws NullPointerException if the provided `javaFileManager` is `null`.
    public InMemoryCompiledClassOutputJavaFileManager(JavaFileManager javaFileManager) {
        Objects.requireNonNull(javaFileManager, "`javaFileManager` cannot be null");
        this.compiledClasses = new HashMap<>();
        super(javaFileManager);
    }

    /// Returns an unmodifiable snapshot of the compiled classes map.
    ///
    /// This method provides access to all classes that have been successfully compiled and stored in memory by this
    /// file manager.
    /// The returned map is a shallow,
    /// unmodifiable copy of the internal map to prevent external callers from accidentally modifying the storage.
    ///
    /// @return a map of fully qualified class names to [InMemoryCompiledClass] instances.
    public Map<String, InMemoryCompiledClass> getCompiledClasses() {
        return Map.copyOf(compiledClasses);
    }

    /// Returns a [JavaFileObject] used by the compiler to write the output of a compilation unit.
    ///
    /// This method overrides the default behavior to redirect the output of compiled Java classes into memory.
    /// It uses a `switch` expression to handle different file kinds:
    /// - `CLASS`: It checks if an [InMemoryCompiledClass] already exists for the given `className` in the internal map.
    ///   If not, it creates a new one and stores it. This ensures that the compiler's output is captured in-memory.
    /// - `SOURCE`, `HTML`, `OTHER`: It delegates the request to the underlying `super` file manager,
    ///   allowing standard file handling for non-class outputs.
    ///
    /// @param location  the location of the file (e.g., `CLASS_OUTPUT`).
    /// @param className the fully qualified name of the class being compiled.
    /// @param kind      the type of the file being requested (e.g., `CLASS`).
    /// @param sibling   the originating source file, or `null` if unknown.
    /// @return the [JavaFileObject] where the compiler will write its data.
    /// @throws IOException if an I/O error occurs during the delegation to the underlying file manager.
    @Override
    public JavaFileObject getJavaFileForOutput(Location location, String className, JavaFileObject.Kind kind, FileObject sibling) throws IOException {
        return switch (kind) {
            case CLASS -> compiledClasses.computeIfAbsent(className, InMemoryCompiledClass::new);
            case SOURCE, HTML, OTHER -> super.getJavaFileForOutput(location, className, kind, sibling);
        };
    }
}
